### ISSUE TITLE
Tattoos

### ISSUE THREAD

**Issue by ladywhimsy** [norcross/ama#1]
I want to get a tattoo on my wrist. Did they hurt? Any tips?

**Comment by norcross** [comment]
They don't hurt as much as other areas, but it's all relative. Since it's a smaller space, any pain is going to be short-lived, as it'll be over before you know it.

As for tips, I would be careful not to go too details on the underside of the wrist, as that rubs on things more than you think. Otherwise, go with a design that you like with an artist you trust.
