### ISSUE TITLE
Coffee

### ISSUE THREAD

**Issue by jazzsequence** [norcross/ama#3]
Light roast, medium roast, dark roast or espresso roast?

**Extra credit:** Starbucks -- meh, awesome or evil incarnate?

**Comment by norcross** [comment]
I actually prefer a light roast. It has more caffeine, and the darker roasts tend to be more bitter and lose some of the flavor. But it depends a lot on where I'm getting it from, as some darker blends are delicious. An espresso roast is great in an actual espresso, otherwise the taste just isn't what I like in a larger cup of coffee.

as for 'Bux, it works in a pinch, but it's usually my last resort. My standard go-to quick coffee is Dunkin.
