### ISSUE TITLE
If you had the option of easily erasing all the tattoos on one part of your body and replacing it with a new giant piece, would you do it? If so, what would you get?

### ISSUE THREAD

**Issue by aaronjorbin** [norcross/ama#6]
Assume that time and money are in infinite quantities.

**Comment by norcross** [comment]
probably not. there's a few on my right arm that I would perhaps remove or replace (mainly because it's kind of a hodge podge of stuff) but overall I like all of them for different reasons.

I've not had any work done on my back yet to avoid that very issue: it will be a full mural style piece, so I am leaving it blank until I make the final decisions on what it'll be.
